export * from './recurrencia.repository';
export * from './ocurrencia.repository';
export * from './materia.repository';
export * from './metacurso.repository';
export * from './contacto.repository';
export * from './cursocohorte.repository';
export * from './horariocurso.repository';
export * from './reunionvideoconferencia.repository';
export * from './cohorte.repository';
